### ISSUE TITLE
No time entry possible on Android 6.0

### ISSUE THREAD

**Issue by ghjp** [koelleChristian/trickytripper#5]
The entry of the date is possible on Android 6. But there is no mask to change the time. The application always chooses the actual time only.

**Comment by koelleChristian** [comment]
I confirm that. The dialog part of the picker which allows you to select the date portion has increased in size with Android 6 so that the time portion of the picker is not visible on screen. I have already fixed this locally. After some further tests with other devices, I expect it to be part of the release due in the next days.
